# Generated by Django 4.1.9 on 2023-05-31 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coor",
            fields=[
                (
                    "FCSKID",
                    models.CharField(
                        db_column="FCSKID",
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FCCODE",
                    models.CharField(
                        db_column="FCCODE", max_length=20, verbose_name="รหัส"
                    ),
                ),
                (
                    "FCNAME",
                    models.CharField(
                        db_column="FCNAME", max_length=20, verbose_name="ชื่อ"
                    ),
                ),
                (
                    "FCSNAME",
                    models.CharField(
                        db_column="FCSNAME", max_length=20, verbose_name="-"
                    ),
                ),
                (
                    "FCNO",
                    models.CharField(
                        db_column="FCNO", max_length=20, verbose_name="เลขที่"
                    ),
                ),
                (
                    "FCFLOOR",
                    models.CharField(
                        db_column="FCFLOOR", max_length=50, verbose_name="ชั้น"
                    ),
                ),
                (
                    "FCROOMNO",
                    models.CharField(
                        db_column="FCROOMNO", max_length=50, verbose_name="ห้อง"
                    ),
                ),
                (
                    "FCBUILDING",
                    models.CharField(
                        db_column="FCBUILDING", max_length=50, verbose_name="-"
                    ),
                ),
                (
                    "FCMOO",
                    models.CharField(
                        db_column="FCMOO", max_length=50, verbose_name="หมู่"
                    ),
                ),
                (
                    "FCSOI",
                    models.CharField(
                        db_column="FCSOI", max_length=50, verbose_name="ซอย"
                    ),
                ),
                (
                    "FCROAD",
                    models.CharField(
                        db_column="FCROAD", max_length=50, verbose_name="ถนน"
                    ),
                ),
                (
                    "FCTAMBON",
                    models.CharField(
                        db_column="FCTAMBON", max_length=50, verbose_name="ตำบล"
                    ),
                ),
                (
                    "FCAMPHUR",
                    models.CharField(
                        db_column="FCAMPHUR", max_length=50, verbose_name="อำเภอ"
                    ),
                ),
                (
                    "FCPROVINCE",
                    models.CharField(
                        db_column="FCPROVINCE", max_length=50, verbose_name="จังหวัด"
                    ),
                ),
                (
                    "FCZIP",
                    models.CharField(
                        db_column="FCZIP", max_length=10, verbose_name="รหัสไปรษณี"
                    ),
                ),
                (
                    "FCBRANCHNM",
                    models.CharField(
                        db_column="FCBRANCHNM", max_length=10, verbose_name="ประเภท"
                    ),
                ),
                (
                    "FMMEMDATA",
                    models.TextField(db_column="FMMEMDATA", verbose_name="หมายเหตุ"),
                ),
                (
                    "FTDATETIME",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="FTDATETIME",
                        verbose_name="สร้างเมื่อ",
                    ),
                ),
                (
                    "FTLASTEDIT",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTEDIT", verbose_name="แก้ไขเมื่อ"
                    ),
                ),
                (
                    "FTLASTUPD",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTUPD", verbose_name="อัพเดทเมื่อ"
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการลูกค้า",
                "verbose_name_plural": "รายการลูกค้า",
                "db_table": "COOR",
            },
        ),
        migrations.CreateModel(
            name="Corp",
            fields=[
                (
                    "FCSKID",
                    models.CharField(
                        db_column="FCSKID",
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FCCODE",
                    models.CharField(
                        db_column="FCCODE", max_length=20, verbose_name="รหัส"
                    ),
                ),
                (
                    "FCNAME",
                    models.CharField(
                        db_column="FCNAME", max_length=50, verbose_name="ชื่อ"
                    ),
                ),
                (
                    "FCNAME2",
                    models.CharField(
                        blank=True,
                        db_column="FCNAME2",
                        max_length=255,
                        verbose_name="ข้อมูลเพิ่มเติม",
                    ),
                ),
                (
                    "FCADDR1",
                    models.CharField(
                        blank=True,
                        db_column="FCADDR1",
                        max_length=50,
                        verbose_name="FCADDR1",
                    ),
                ),
                (
                    "FCADDR12",
                    models.CharField(
                        blank=True,
                        db_column="FCADDR12",
                        max_length=50,
                        verbose_name="FCADDR12",
                    ),
                ),
                (
                    "FCADDR2",
                    models.CharField(
                        blank=True,
                        db_column="FCADDR22",
                        max_length=50,
                        verbose_name="FCADDR22",
                    ),
                ),
                (
                    "FCTEL",
                    models.CharField(
                        blank=True,
                        db_column="FCTEL",
                        max_length=50,
                        verbose_name="FCTEL",
                    ),
                ),
                (
                    "FCFAX",
                    models.CharField(
                        blank=True,
                        db_column="FCFAX",
                        max_length=50,
                        verbose_name="FCFAX",
                    ),
                ),
                (
                    "FTDATETIME",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="FTDATETIME",
                        verbose_name="สร้างเมื่อ",
                    ),
                ),
                (
                    "FTLASTEDIT",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTEDIT", verbose_name="แก้ไขเมื่อ"
                    ),
                ),
                (
                    "FTLASTUPD",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTUPD", verbose_name="อัพเดทเมื่อ"
                    ),
                ),
                (
                    "FCTAXID",
                    models.CharField(
                        blank=True,
                        db_column="FCTAXID",
                        max_length=50,
                        verbose_name="FCTAXID",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายชื่อบริษัท",
                "verbose_name_plural": "รายชื่อบริษัท",
                "db_table": "CORP",
            },
        ),
        migrations.CreateModel(
            name="Dept",
            fields=[
                (
                    "FCSKID",
                    models.CharField(
                        db_column="FCSKID",
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FCCODE",
                    models.CharField(
                        db_column="FCCODE", max_length=20, verbose_name="รหัส"
                    ),
                ),
                (
                    "FCNAME",
                    models.CharField(
                        db_column="FCNAME", max_length=20, verbose_name="ชื่อ"
                    ),
                ),
                (
                    "FCNAME2",
                    models.CharField(
                        db_column="FCNAME2",
                        max_length=20,
                        verbose_name="ข้อมูลเพิ่มเติม",
                    ),
                ),
                (
                    "FTDATETIME",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="FTDATETIME",
                        verbose_name="สร้างเมื่อ",
                    ),
                ),
                (
                    "FTLASTEDIT",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTEDIT", verbose_name="แก้ไขเมื่อ"
                    ),
                ),
                (
                    "FTLASTUPD",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTUPD", verbose_name="อัพเดทเมื่อ"
                    ),
                ),
                (
                    "FCCORP",
                    models.ForeignKey(
                        db_column="FCCORP",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vcst.corp",
                        verbose_name="บริษัท",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลฝ่าย",
                "verbose_name_plural": "ข้อมูลฝ่าย",
                "db_table": "DEPT",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "FCSKID",
                    models.CharField(
                        db_column="FCSKID",
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FCLOGIN",
                    models.CharField(
                        db_column="FCLOGIN", max_length=20, verbose_name="รหัส"
                    ),
                ),
                (
                    "FCPW",
                    models.CharField(
                        db_column="FCPW", max_length=20, verbose_name="รหัสผ่าน"
                    ),
                ),
                (
                    "FCRCODE",
                    models.CharField(
                        db_column="FCRCODE", max_length=20, verbose_name="ชื่อ"
                    ),
                ),
                (
                    "FTDATETIME",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="FTDATETIME",
                        verbose_name="สร้างเมื่อ",
                    ),
                ),
                (
                    "FTLASTEDIT",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTEDIT", verbose_name="แก้ไขเมื่อ"
                    ),
                ),
                (
                    "FTLASTUPD",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTUPD", verbose_name="อัพเดทเมื่อ"
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการผู้ใช้งาน",
                "verbose_name_plural": "รายการผู้ใช้งาน",
                "db_table": "EMPLR",
            },
        ),
        migrations.CreateModel(
            name="PdGrd",
            fields=[
                (
                    "FCSKID",
                    models.CharField(
                        db_column="FCSKID",
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FCCODE",
                    models.CharField(
                        db_column="FCCODE", max_length=20, verbose_name="รหัส"
                    ),
                ),
                (
                    "FCNAME",
                    models.CharField(
                        db_column="FCNAME", max_length=20, verbose_name="ชื่อ"
                    ),
                ),
                (
                    "FCNAME2",
                    models.CharField(
                        db_column="FCNAME2",
                        max_length=20,
                        verbose_name="ข้อมูลเพิ่มเติม",
                    ),
                ),
                (
                    "FTDATETIME",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="FTDATETIME",
                        verbose_name="สร้างเมื่อ",
                    ),
                ),
                (
                    "FTLASTEDIT",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTEDIT", verbose_name="แก้ไขเมื่อ"
                    ),
                ),
                (
                    "FTLASTUPD",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTUPD", verbose_name="อัพเดทเมื่อ"
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลกลุ่ม",
                "verbose_name_plural": "กลุ่มสินค้า",
                "db_table": "PDGRP",
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "FCSKID",
                    models.CharField(
                        db_column="FCSKID",
                        editable=False,
                        max_length=8,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FCCODE",
                    models.CharField(
                        db_column="FCCODE",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัส",
                    ),
                ),
                (
                    "FCNAME",
                    models.CharField(
                        db_column="FCNAME", max_length=20, verbose_name="ชื่อ"
                    ),
                ),
                (
                    "FCNAME2",
                    models.CharField(
                        db_column="FCNAME2",
                        max_length=20,
                        verbose_name="ข้อมูลเพิ่มเติม",
                    ),
                ),
                (
                    "FTDATETIME",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="FTDATETIME",
                        verbose_name="สร้างเมื่อ",
                    ),
                ),
                (
                    "FTLASTEDIT",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTEDIT", verbose_name="แก้ไขเมื่อ"
                    ),
                ),
                (
                    "FTLASTUPD",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTUPD", verbose_name="อัพเดทเมื่อ"
                    ),
                ),
            ],
            options={
                "verbose_name": "ประเภทสินค้า",
                "verbose_name_plural": "ประเภทสินค้า",
                "db_table": "PRODTYPE",
            },
        ),
        migrations.CreateModel(
            name="Um",
            fields=[
                (
                    "FCSKID",
                    models.CharField(
                        db_column="FCSKID",
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FCCODE",
                    models.CharField(
                        db_column="FCCODE", max_length=20, verbose_name="รหัส"
                    ),
                ),
                (
                    "FCNAME",
                    models.CharField(
                        db_column="FCNAME", max_length=20, verbose_name="ชื่อ"
                    ),
                ),
                (
                    "FCNAME2",
                    models.CharField(
                        db_column="FCNAME2",
                        max_length=20,
                        verbose_name="ข้อมูลเพิ่มเติม",
                    ),
                ),
                (
                    "FTDATETIME",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="FTDATETIME",
                        verbose_name="สร้างเมื่อ",
                    ),
                ),
                (
                    "FTLASTEDIT",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTEDIT", verbose_name="แก้ไขเมื่อ"
                    ),
                ),
                (
                    "FTLASTUPD",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTUPD", verbose_name="อัพเดทเมื่อ"
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลหน่วยสินค้า",
                "verbose_name_plural": "หน่วยสินค้า",
                "db_table": "UM",
            },
        ),
        migrations.CreateModel(
            name="Whouse",
            fields=[
                (
                    "FCSKID",
                    models.CharField(
                        db_column="FCSKID",
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FCCODE",
                    models.CharField(
                        db_column="FCCODE", max_length=20, verbose_name="รหัส"
                    ),
                ),
                (
                    "FCNAME",
                    models.CharField(
                        db_column="FCNAME", max_length=20, verbose_name="ชื่อ"
                    ),
                ),
                (
                    "FCNAME2",
                    models.CharField(
                        db_column="FCNAME2",
                        max_length=20,
                        verbose_name="ข้อมูลเพิ่มเติม",
                    ),
                ),
                (
                    "FTDATETIME",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="FTDATETIME",
                        verbose_name="สร้างเมื่อ",
                    ),
                ),
                (
                    "FTLASTEDIT",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTEDIT", verbose_name="แก้ไขเมื่อ"
                    ),
                ),
                (
                    "FTLASTUPD",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTUPD", verbose_name="อัพเดทเมื่อ"
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลคลังสินค้า",
                "verbose_name_plural": "คลังสินค้า",
                "db_table": "WHOUSE",
            },
        ),
        migrations.CreateModel(
            name="Sect",
            fields=[
                (
                    "FCSKID",
                    models.CharField(
                        db_column="FCSKID",
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FCCODE",
                    models.CharField(
                        db_column="FCCODE", max_length=20, verbose_name="รหัส"
                    ),
                ),
                (
                    "FCNAME",
                    models.CharField(
                        db_column="FCNAME", max_length=20, verbose_name="ชื่อ"
                    ),
                ),
                (
                    "FCNAME2",
                    models.CharField(
                        db_column="FCNAME2",
                        max_length=20,
                        verbose_name="ข้อมูลเพิ่มเติม",
                    ),
                ),
                (
                    "FTDATETIME",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="FTDATETIME",
                        verbose_name="สร้างเมื่อ",
                    ),
                ),
                (
                    "FTLASTEDIT",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTEDIT", verbose_name="แก้ไขเมื่อ"
                    ),
                ),
                (
                    "FTLASTUPD",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTUPD", verbose_name="อัพเดทเมื่อ"
                    ),
                ),
                (
                    "FCCORP",
                    models.ForeignKey(
                        db_column="FCCORP",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vcst.corp",
                        verbose_name="บริษัท",
                    ),
                ),
                (
                    "FCDEPT",
                    models.ForeignKey(
                        db_column="FCDEPT",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vcst.dept",
                        verbose_name="ฝ่าย",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลแผนก",
                "verbose_name_plural": "ข้อมูลแผนก",
                "db_table": "SECT",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "FCSKID",
                    models.CharField(
                        db_column="FCSKID",
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FCCODE",
                    models.CharField(
                        db_column="FCCODE", max_length=20, verbose_name="รหัส"
                    ),
                ),
                (
                    "FCNAME",
                    models.CharField(
                        db_column="FCNAME", max_length=20, verbose_name="ชื่อ"
                    ),
                ),
                (
                    "FCNAME2",
                    models.CharField(
                        db_column="FCNAME2", max_length=20, verbose_name="เพิ่มเติม1"
                    ),
                ),
                (
                    "FCSNAME",
                    models.CharField(
                        db_column="FCSNAME", max_length=20, verbose_name="เพิ่มเติม2"
                    ),
                ),
                (
                    "FCSNAME2",
                    models.CharField(
                        db_column="FCSNAME2", max_length=20, verbose_name="เพิ่มเติม3"
                    ),
                ),
                (
                    "FCDATASER",
                    models.CharField(
                        db_column="FCDATASER",
                        editable=False,
                        max_length=20,
                        verbose_name="รหัสจำเพราะ",
                    ),
                ),
                (
                    "FTDATETIME",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="FTDATETIME",
                        verbose_name="สร้างเมื่อ",
                    ),
                ),
                (
                    "FTLASTEDIT",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTEDIT", verbose_name="แก้ไขเมื่อ"
                    ),
                ),
                (
                    "FTLASTUPD",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTUPD", verbose_name="อัพเดทเมื่อ"
                    ),
                ),
                (
                    "FCCORP",
                    models.ForeignKey(
                        db_column="FCCORP",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vcst.corp",
                        verbose_name="ชื่อบริษัท",
                    ),
                ),
                (
                    "FCPDGRP",
                    models.ForeignKey(
                        db_column="FCPDGRP",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vcst.pdgrd",
                        verbose_name="กลุ่ม",
                    ),
                ),
                (
                    "FCTYPE",
                    models.ForeignKey(
                        db_column="FCTYPE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vcst.producttype",
                        verbose_name="ประเภท",
                    ),
                ),
                (
                    "FCUM",
                    models.ForeignKey(
                        db_column="FCUM",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vcst.um",
                        verbose_name="หน่วย",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการข้อมูลสินค้า",
                "verbose_name_plural": "รายการสินค้า",
                "db_table": "PROD",
            },
        ),
        migrations.CreateModel(
            name="Glref",
            fields=[
                (
                    "FCBOOK",
                    models.CharField(
                        db_column="FCBOOK", max_length=8, verbose_name="เล่มเอกสาร"
                    ),
                ),
                (
                    "FCBRANCH",
                    models.CharField(
                        db_column="FCBRANCH",
                        max_length=8,
                        verbose_name="พื้นที่จังหวัด",
                    ),
                ),
                (
                    "FCCODE",
                    models.CharField(
                        db_column="FCCODE",
                        editable=False,
                        max_length=20,
                        verbose_name="รหัส",
                    ),
                ),
                (
                    "FCDATASER",
                    models.CharField(
                        db_column="FCDATASER",
                        editable=False,
                        max_length=8,
                        verbose_name="APPID",
                    ),
                ),
                (
                    "FCREFNO",
                    models.CharField(
                        db_column="FCREFNO",
                        editable=False,
                        max_length=20,
                        verbose_name="เลขที่เอกสารอ้างอิง",
                    ),
                ),
                (
                    "FCSKID",
                    models.CharField(
                        db_column="FCSKID",
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FCSTEP",
                    models.CharField(
                        db_column="FCSTEP", max_length=5, verbose_name="I/O"
                    ),
                ),
                (
                    "FNAMT",
                    models.DecimalField(
                        db_column="FNAMT",
                        decimal_places=2,
                        max_digits=2,
                        verbose_name="จำนวน",
                    ),
                ),
                (
                    "FTDATETIME",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="FTDATETIME",
                        verbose_name="สร้างเมื่อ",
                    ),
                ),
                (
                    "FTLASTEDIT",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTEDIT", verbose_name="แก้ไขเมื่อ"
                    ),
                ),
                (
                    "FTLASTUPD",
                    models.DateTimeField(
                        auto_now=True, db_column="FTLASTUPD", verbose_name="อัพเดทเมื่อ"
                    ),
                ),
                (
                    "FCLUPDAPP",
                    models.CharField(
                        db_column="FCLUPDAPP",
                        editable=False,
                        max_length=8,
                        verbose_name="FCLUPDAPP",
                    ),
                ),
                (
                    "FMMEMDATA",
                    models.TextField(
                        db_column="FMMEMDATA", editable=False, verbose_name="หมายเหตุ"
                    ),
                ),
                (
                    "FCCOOR",
                    models.ForeignKey(
                        db_column="FCCOOR",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vcst.coor",
                        verbose_name="ลูกค้า",
                    ),
                ),
                (
                    "FCCORP",
                    models.ForeignKey(
                        db_column="FCCORP",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vcst.corp",
                        verbose_name="ชื่อบริษัท",
                    ),
                ),
                (
                    "FCCORRECTB",
                    models.ForeignKey(
                        db_column="FCCORRECTB",
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vcst.employee",
                        verbose_name="ชื่อบริษัท",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการ GLREF",
                "verbose_name_plural": "รายการ GLREF",
                "db_table": "GLREF",
            },
        ),
        migrations.AddField(
            model_name="coor",
            name="FCCORP",
            field=models.ForeignKey(
                db_column="FCCORP",
                on_delete=django.db.models.deletion.CASCADE,
                to="vcst.corp",
                verbose_name="ชื่อบริษัท",
            ),
        ),
    ]
