"""
Django settings for webbase project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nsgxlr&%4($w%r*zb7u&5$#!wqq-=4+rk#dmskg@+8_x(28bx$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vcst.apps.VcstConfig',
    'receives.apps.ReceivesConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webbase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webbase.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "django_db",
        "USER": "postgres",
        "PASSWORD": "admin@1234",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    },
    "aaa": {
        "ENGINE": "mssql",
        "NAME": "AAA",
        "USER": "fm1234",
        "PASSWORD": "x2y2",
        "HOST": "192.168.10.6",
        "PORT": "1433",
        "Trusted_Connection": "no",
        "OPTIONS": {
            'driver': 'FreeTDS',
            'unicode_results': True,
            'host_is_server': True,
            'driver_supports_utf8': True,
            'extra_params': 'tds_version=7.4',
        },
    },
    "formula_aaa": {
        "ENGINE": "mssql",
        "NAME": "formula",
        "USER": "fm1234",
        "PASSWORD": "x2y2",
        "HOST": "192.168.10.6",
        "PORT": "1433",
        "Trusted_Connection": "no",
        "OPTIONS": {
            'driver': 'FreeTDS',
            'unicode_results': True,
            'host_is_server': True,
            'driver_supports_utf8': True,
            'extra_params': 'tds_version=7.4',
        },
    },
    "bvs": {
        "ENGINE": "mssql",
        "NAME": "BVS",
        "USER": "fm1234",
        "PASSWORD": "x2y2",
        "HOST": "192.168.1.191",
        "PORT": "1433",
        "Trusted_Connection": "no",
        "OPTIONS": {
            'driver': 'FreeTDS',
            'unicode_results': True,
            'host_is_server': True,
            'driver_supports_utf8': True,
            'extra_params': 'tds_version=7.4',
        },
    },
    "formula_bvs": {
        "ENGINE": "mssql",
        "NAME": "formula",
        "USER": "fm1234",
        "PASSWORD": "x2y2",
        "HOST": "192.168.1.191",
        "PORT": "1433",
        "Trusted_Connection": "no",
        "OPTIONS": {
            'driver': 'FreeTDS',
            'unicode_results': True,
            'host_is_server': True,
            'driver_supports_utf8': True,
            'extra_params': 'tds_version=7.4',
        },
    },
    "vcs": {
        "ENGINE": "mssql",
        "NAME": "VCS",
        "USER": "fm1234",
        "PASSWORD": "x2y2",
        "HOST": "192.168.5.12",
        "PORT": "1433",
        "Trusted_Connection": "no",
        "OPTIONS": {
            'driver': 'FreeTDS',
            'unicode_results': True,
            'host_is_server': True,
            'driver_supports_utf8': True,
            'extra_params': 'tds_version=7.4',
        },
    },
    "formula_vcs": {
        "ENGINE": "mssql",
        "NAME": "formula",
        "USER": "fm1234",
        "PASSWORD": "x2y2",
        "HOST": "192.168.5.12",
        "PORT": "1433",
        "Trusted_Connection": "no",
        "OPTIONS": {
            'driver': 'FreeTDS',
            'unicode_results': True,
            'host_is_server': True,
            'driver_supports_utf8': True,
            'extra_params': 'tds_version=7.4',
        },
    },
    "vcst": {
        "ENGINE": "mssql",
        "NAME": "VCST",
        "USER": "fm1234",
        "PASSWORD": "x2y2",
        "HOST": "192.168.20.9",
        "PORT": "1433",
        "Trusted_Connection": "no",
        "OPTIONS": {
            'driver': 'FreeTDS',
            'unicode_results': True,
            'host_is_server': True,
            'driver_supports_utf8': True,
            'extra_params': 'tds_version=7.4',
        },
    },
    "formula_vcst": {
        "ENGINE": "mssql",
        "NAME": "Formula",
        "USER": "fm1234",
        "PASSWORD": "x2y2",
        "HOST": "192.168.20.9",
        "PORT": "1433",
        "Trusted_Connection": "no",
        "OPTIONS": {
            'driver': 'FreeTDS',
            'unicode_results': True,
            'host_is_server': True,
            'driver_supports_utf8': True,
            'extra_params': 'tds_version=7.4',
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATABASE_ROUTERS = ["vcst.db.DBRouter"]
