# Generated by Django 4.1.9 on 2023-05-31 09:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReceiveEnties",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "receive_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่รับ"
                    ),
                ),
                (
                    "book_id",
                    models.CharField(max_length=8, verbose_name="เล่มที่เอกสาร"),
                ),
                ("whs_id", models.CharField(max_length=8, verbose_name="คลังสินค้า")),
                (
                    "invoice_no",
                    models.CharField(max_length=20, verbose_name="เลขที่ Invoice"),
                ),
                ("coor_id", models.CharField(max_length=8, verbose_name="ผู้ขาย")),
                (
                    "sect_id",
                    models.CharField(editable=False, max_length=8, verbose_name="แผนก"),
                ),
                ("po_no", models.CharField(max_length=20, verbose_name="เลขที่ PO")),
                ("remark", models.TextField(verbose_name="หมายเหตุ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("0", "Adjust"),
                            ("1", "Waiting"),
                            ("2", "Success"),
                            ("3", "Failed"),
                        ],
                        max_length=1,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "sync",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="สถานะซิงค์ข้อมูล"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="แก้ไขเมื่อ"),
                ),
            ],
            options={
                "verbose_name": "1.ข้อมูลการรับสินค้า(Enties)",
                "verbose_name_plural": "1.ข้อมูลการรับสินค้า(Enties)",
                "db_table": "tbt_receive_enties",
            },
        ),
        migrations.CreateModel(
            name="ReceiveDetail",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("product_id", models.CharField(max_length=8, verbose_name="สินค้า")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, verbose_name="จำนวนที่รับ"
                    ),
                ),
                ("unit_id", models.CharField(max_length=8, verbose_name="หน่วย")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, verbose_name="ราคาต่อหน่วย"
                    ),
                ),
                ("status", models.BooleanField(editable=False, verbose_name="สถานะ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="แก้ไขเมื่อ"),
                ),
                (
                    "receive_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="receives.receiveenties",
                        verbose_name="เล่มที่เอกสาร",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.ข้อมูลการรับสินค้า(Detail)",
                "verbose_name_plural": "2.ข้อมูลการรับสินค้า(Detail)",
                "db_table": "tbt_receive_detail",
            },
        ),
    ]
